---
- name: Create hadoop_tar directory
  hosts: servers
  become: yes
  vars_files:
    - /data/work/hadoop_3.3.5_ansible/main.yml
  tasks:
    - name: Create hadoop_tar directory
      file:
        path: "{{ hadoop_tar_path }}"
        state: directory

    - name: Create work directory
      file:
        path: "{{ work_dir }}"
        state: directory


- name: Copy hadoop_tar to servers
  hosts: localhost
  become: yes
  vars_files:
    - /data/work/hadoop_3.3.5_ansible/main.yml
  tasks:
    - name: tar_scp.sh Start
      shell: "{{ play_book_dir }}/tar_scp.sh {{ play_book_dir }} {{ hadoop_tar_path }}"

- name: Extract hadoop_tar
  hosts: servers
  become: yes
  vars_files:
    - /data/work/hadoop_3.3.5_ansible/main.yml
  tasks:
    - name: Extract the hadoop tarball
      unarchive:
        src: "{{ hadoop_tar_path }}/{{ hadoop_tar_filename }}"
        dest: "{{ work_dir }}"
        remote_src: yes


- name: entrypoint_sh start
  hosts: localhost
  become: yes
  vars_files:
    - /data/work/hadoop_3.3.5_ansible/main.yml
  tasks:
    - name: entry_point_sh start
      shell: "{{ play_book_dir }}/entrypoint.sh {{ play_book_dir }} {{ work_dir }}"
